language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t muasif80/react-test -f ./client/Dockerfile.dev ./client # multiple lines for multiple builds
script:
  - docker run -e CI=true muasif80/react-test npm test # multiple lines for each of the docker containers for tests

after_success:
  - docker build -t muasif80/multi-client ./client
  - docker build -t muasif80/multi-nginx ./nginx
  - docker build -t muasif80/multi-server ./server
  - docker build -t muasif80/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push muasif80/multi-client
  - docker push muasif80/multi-nginx
  - docker push muasif80/multi-server
  - docker push muasif80/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-985910981670'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY